snippet should return 2 for ERROR
git-svn-id: http://audit-test.svn.sourceforge.net/svnroot/audit-test/trunk/tests@804 df539fd5-5ffc-0310-83f5-f045c3a6a7d5

diff --git a/audit/README b/audit/README
--- a/audit/README
+++ b/audit/README
@@ -58,7 +58,7 @@ The library should be loaded with this snippet at the top of the test case:
                 cd ..
             done
             exit 1
-        ) || { echo "Can't find TOPDIR, where is rules.mk?" >&2; exit 1; }
+        ) || { echo "Can't find TOPDIR, where is rules.mk?" >&2; exit 2; }
         export TOPDIR
     fi
     PATH=$TOPDIR/utils:$PATH
