Reorganize test harness into utils directory.  Remove the need for symlinking run.bash.  Add $(TOPDIR)/utils to the path by default when running tests under the harness.
Rename run.bash -> harness
Rename run.conf -> harness.conf



git-svn-id: http://audit-test.svn.sourceforge.net/svnroot/audit-test/trunk/tests@600 df539fd5-5ffc-0310-83f5-f045c3a6a7d5

diff --git a/audit/utils/harness b/audit/utils/harness
--- a/audit/utils/harness
+++ b/audit/utils/harness
@@ -44,14 +44,8 @@ declare exit_status
 declare logging=false
 declare opt_verbose=false
 declare opt_debug=false
-declare opt_config=run.conf
-declare opt_log=run.log
-
-#----------------------------------------------------------------------
-# test environment
-#----------------------------------------------------------------------
-
-export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+declare opt_config=harness.conf
+declare opt_log=harness.log
 
 #----------------------------------------------------------------------
 # utility functions
@@ -120,13 +114,13 @@ function prf {
 #----------------------------------------------------------------------
 
 # make_variation(char *cmdline, char *variation)
-# This is just the default implementation; it can be overridden in run.conf
+# This is just the default implementation; it can be overridden in harness.conf
 function make_variation {
     echo "$1 $2"
 }
 
 # run_test(char *cmdline)
-# This is just the default implementation; it can be overridden in run.conf
+# This is just the default implementation; it can be overridden in harness.conf
 function run_test {
     eval "$1"
 }
@@ -203,12 +197,12 @@ function - {
 
 trap 'cleanup; close_log; exit' 0 1 2 3 15
 
-# this can be overridden in run.conf
+# this can be overridden in harness.conf
 function startup_hook {
     true
 }
 
-# this can be overridden in run.conf
+# this can be overridden in harness.conf
 function cleanup_hook {
     true
 }
@@ -267,6 +261,16 @@ function close_log {
 }
 
 #----------------------------------------------------------------------
+# test environment
+#----------------------------------------------------------------------
+
+export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+[[ -n $TOPDIR ]] || die "Please set TOPDIR in environment"
+pushd $TOPDIR >/dev/null || die "Can't access TOPDIR ($TOPDIR)"
+PATH=$PWD/utils:$PATH
+popd >/dev/null
+
+#----------------------------------------------------------------------
 # main program
 #----------------------------------------------------------------------
 
@@ -275,7 +279,7 @@ function usage {
 Usage: ${0##*/} [OPTION]...
 Run a set of test cases, reporting pass/fail and tallying results.
 
-    -f --config=FILE  Use a config file other than run.conf
+    -f --config=FILE  Use a config file other than harness.conf
     -l --log=FILE     Output to a log other than run.log
     -h --help         Show this help
 
