introduce install/uninstall targets on a global level
The final idea is to consolidate all install/uninstall operations
under a single, unified command.

Since some directories already had 'install' and/or 'uninstall', their
logic had to be modified to not interfere with the 'install' being run
from the top directory.

This unfortunately cannot include selinux-policy as it needs to be
installed prior to any other install targets, manually - some of the
install scripts require access that only lspp_test_r can provide.

Signed-off-by: Jiri Jaburek <jjaburek@redhat.com>

diff --git a/audit-test/utils/selinux-policy/Makefile b/audit-test/utils/selinux-policy/Makefile
--- a/audit-test/utils/selinux-policy/Makefile
+++ b/audit-test/utils/selinux-policy/Makefile
@@ -14,6 +14,10 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ###############################################################################
 
+TOPDIR		= ../..
+
+include $(TOPDIR)/rules.mk
+
 #######
 #
 # LSPP test Makefile
@@ -21,49 +25,33 @@
 #
 
 SELINUX_POLICY_TYPE := mls
-SELINUX_POLICY_RPM := selinux-policy-$(SELINUX_POLICY_TYPE)
-SELINUX_DEV_RPM := selinux-policy
-
 SELINUX_POLICY_DEFTYPEFILE := /etc/selinux/$(SELINUX_POLICY_TYPE)/contexts/default_type
 SELINUX_POLICY_STAFFUCONTEXTS := /etc/selinux/$(SELINUX_POLICY_TYPE)/contexts/users/staff_u
 TEST_STAFFUCONTEXTS := "lspp_test_r:local_login_t:s0       staff_r:staff_t:s0 sysadm_r:sysadm_t:s0"
 
-SELINUX_DEV_BASEDIR := /usr/share/selinux/devel
-
-
-TEST_BASEDIR := /usr/local/eal4_testing
+TEST_BASEDIR := $(shell realpath $(TOPDIR))
+SELINUX_DEV_MAKEFILE := /usr/share/selinux/devel/Makefile
 
 SELINUX_USER := staff_u
 
 MODULE_NAME := lspp_test
-MODULE_ROLE := lspp_test_r:lspp_harness_t
+MODULE_ROLE := lspp_test_r
+MODULE_DEFTYPE := lspp_harness_t
 
 ###
 #
 # targets
 #
 
-.PHONY: verify install uninstall relabel distclean
+# only in selinux mls mode
+ifeq ($(call sepol,mls),1)
 
-# base SELinux module targets
-include $(SELINUX_DEV_BASEDIR)/Makefile
+all: $(MODULE_NAME).pp
+
+$(MODULE_NAME).pp:
+	$(MAKE) -f $(SELINUX_DEV_MAKEFILE)
 
 verify:
-	@echo "Checking system for basic requirements"
-	@echo -n " SELinux policy RPM version ($(SELINUX_POLICY_RPM)): "; \
-	if rpm -q $(SELINUX_POLICY_RPM) > /dev/null; then \
-		rpm -q $(SELINUX_POLICY_RPM) --qf "%{VERSION}-%{RELEASE}"; \
-		echo ""; \
-	else \
-		echo "not installed"; \
-	fi;
-	@echo -n " SELinux policy development RPM version: "; \
-	if rpm -q $(SELINUX_DEV_RPM) > /dev/null; then \
-		rpm -q $(SELINUX_DEV_RPM) --qf "%{VERSION}-%{RELEASE}"; \
-		echo ""; \
-	else \
-		echo "not installed"; \
-	fi;
 	@echo -n " LSPP test policy module version: "; \
 	if semodule -l | grep -q $(MODULE_NAME); then \
 		semodule -l | grep $(MODULE_NAME) | cut -f 2; \
@@ -71,8 +59,7 @@ verify:
 		echo "not installed"; \
 	fi;
 	@echo -n " Checking test login context: "; \
-	role=$$(echo $(MODULE_ROLE) | cut -d':' -f 1); \
-	if grep -q $$role $(SELINUX_POLICY_STAFFUCONTEXTS); then \
+	if grep -q $(MODULE_ROLE) $(SELINUX_POLICY_STAFFUCONTEXTS); then \
 		echo "installed"; \
 	else \
 		echo "not installed"; \
@@ -86,9 +73,9 @@ verify:
 
 install: $(MODULE_NAME).pp
 	@echo "$$(id -Z)" | egrep -q "(secadm_r|lspp_test_r)" || { echo \
-		"Error: You need to be in secadm_r or lspp_test_r role to install/upgrade SELinux policy module"; \
-		exit 1; }
-	@if semodule -l | grep -q $(MODULE_NAME); then \
+		"Notice: secadm_r role is needed to install/upgrade SELinux policy module"; \
+		newrole -r secadm_r -- -c "$(MAKE) install"; exit $$?; }; \
+	if semodule -l | grep -q $(MODULE_NAME); then \
 		echo -n "Upgrading $(MODULE_NAME) module ... "; \
 		semodule -u $(MODULE_NAME).pp &> /dev/null && echo "ok" || \
 			echo "failed (check the policy version number)"; \
@@ -96,61 +83,67 @@ install: $(MODULE_NAME).pp
 		echo -n "Loading $(MODULE_NAME) module ... "; \
 		semodule -i $(MODULE_NAME).pp &> /dev/null && echo "ok" || \
 			echo "failed"; \
-		role=$$(echo $(MODULE_ROLE) | cut -d':' -f 1); \
 		range='s0-s15:c0.c1023'; \
 		existing_roles=$$(semanage user -l | grep "^$(SELINUX_USER)" | awk 'sub("^.*[ \t]"$$5,$$5)'); \
-		if [ -n "$$role" -a -n "$$existing_roles" ]; then \
-			echo -n "Adding additional role \"$$role\" to user \"$(SELINUX_USER)\" ... "; \
-			semanage user -m -r "$$range" -R "$$existing_roles $$role" $(SELINUX_USER) &> /dev/null && \
+		if [ "$$existing_roles" ]; then \
+			echo -n "Adding additional role \"$(MODULE_ROLE)\" to user \"$(SELINUX_USER)\" ... "; \
+			semanage user -m -r "$$range" -R "$$existing_roles $(MODULE_ROLE)" $(SELINUX_USER) &> /dev/null && \
 				echo "ok" || \
 				echo "failed (check the SELinux user)"; \
 			echo "Adding role/type to the default_types file"; \
-			echo $(MODULE_ROLE) >> $(SELINUX_POLICY_DEFTYPEFILE); \
+			echo $(MODULE_ROLE):$(MODULE_DEFTYPE) >> $(SELINUX_POLICY_DEFTYPEFILE); \
 		fi; \
 	fi; \
 	echo -n "Adding test login context ..."; \
-	role=$$(echo $(MODULE_ROLE) | cut -d':' -f 1); \
-        if grep -q $$role $(SELINUX_POLICY_STAFFUCONTEXTS); then \
-                echo "already installed"; \
-        else \
+	if grep -q $(MODULE_ROLE) $(SELINUX_POLICY_STAFFUCONTEXTS); then \
+		echo "already installed"; \
+	else \
 		echo $(TEST_STAFFUCONTEXTS) >> $(SELINUX_POLICY_STAFFUCONTEXTS);\
-                echo "added"; \
-        fi;
+		echo "added"; \
+	fi; \
+	$(MAKE) relabel
 
 uninstall:
-	@echo "$$(id -Z)" | grep -q "secadm_r" || \
-		{ echo "Error: You need to be in secadm_r role to install lspp_test SELinux policy module"; exit 1; }
-	@role=$$(echo $(MODULE_ROLE) | cut -d':' -f 1); \
-	if [ -n "$$role" ]; then \
-		echo "Removing role/type from the default_types file"; \
-		sed -i -e '/$(MODULE_ROLE)/d' $(SELINUX_POLICY_DEFTYPEFILE); \
-		echo -n "Removing local customizations from user \"$(SELINUX_USER)\" ... "; \
-		semanage user -d $(SELINUX_USER) &> /dev/null && \
-			echo "ok" || echo "failed"; \
-	fi; \
+	@echo "$$(ps -AZ)" | grep -q "lspp_test_r" && { echo \
+		"Error: lspp_test_r is used by active sessions, cannot remove"; exit 1; } || true
+	@echo "$$(id -Z)" | grep -q "secadm_r" || { echo \
+		"Notice: secadm_r role is needed to uninstall SELinux policy module"; \
+		en=$$(getenforce | grep -q Enforcing && echo 1 || echo 0); \
+		newrole -r secadm_r -- -c "setenforce 0; $(MAKE) uninstall; setenforce $$en"; exit $$?; }; \
+	echo "Removing role/type from the default_types file"; \
+	sed -i -e '/$(MODULE_ROLE):$(MODULE_DEFTYPE)/d' $(SELINUX_POLICY_DEFTYPEFILE); \
+	existing_roles=$$(semanage user -l | grep "^$(SELINUX_USER)" | awk 'sub("^.*[ \t]"$$5,$$5)'); \
+	new_roles=$$(echo $$existing_roles | sed 's/$(MODULE_ROLE)//'); \
+	echo -n "Removing $(MODULE_ROLE) from user \"$(SELINUX_USER)\" ... "; \
+	semanage user -m -R "$$new_roles" $(SELINUX_USER) &> /dev/null && \
+		echo "ok" || echo "failed"; \
 	echo -n "Unloading $(MODULE_NAME) module ... "; \
 	semodule -r $(MODULE_NAME) &> /dev/null && echo "ok" || echo "failed"; \
 	echo -n "Removing test login context ...";  \
-	if grep -q $$role $(SELINUX_POLICY_STAFFUCONTEXTS); then \
-		sed -i -e /$$role/d $(SELINUX_POLICY_STAFFUCONTEXTS); \
+	if grep -q $(MODULE_ROLE) $(SELINUX_POLICY_STAFFUCONTEXTS); then \
+		sed -i -e /$(MODULE_ROLE)/d $(SELINUX_POLICY_STAFFUCONTEXTS); \
 		echo "removed"; \
 	else \
 		echo "not installed"; \
-	fi;
+	fi; \
+	$(MAKE) relabel
 
+.PHONY: relabel
 relabel:
-	@echo "Resetting file ownership in $(TEST_BASEDIR)"
-	@chown -R root:root $(TEST_BASEDIR)
-	@echo "Relabeling LSPP tests in $(TEST_BASEDIR)"
+	@echo "Relabeling LSPP tests"
 	@restorecon -Fr $(TEST_BASEDIR)
+
+clean:
+	$(MAKE) -f $(SELINUX_DEV_MAKEFILE) clean
 
 # remove only generated files
 distclean:
-	$(MAKE) clean
-	@ shopt -s nullglob; \
+	@shopt -s nullglob; \
 	for file in *.fc; do \
 		[ -z "$$(cat $$file)" ] && rm -vf "$$file"; \
 	done; \
 	for file in *.if; do \
 		[ -z "$$(grep -v '<summary></summary>' < $$file)" ] && rm -vf "$$file"; \
 	done;
+
+endif
