utils: disable color on outputs without color support
Signed-off-by: Jiri Jaburek <jjaburek@redhat.com>

diff --git a/audit-test/utils/envcheck b/audit-test/utils/envcheck
--- a/audit-test/utils/envcheck
+++ b/audit-test/utils/envcheck
@@ -60,6 +60,7 @@
 # $3 = optional cmd text to show instead of $1
 # returns the command's exit code
 # and sets CHECK_FAILED var to nonempty value upon fail
+incolor() { [ -t 1 -a "$(tput colors)" -ge 8 ]; }
 check()
 {
     [ $# -lt 1 ] && return 1
@@ -68,9 +69,9 @@ check()
 
     # echo initial msg
     if [ "$msg" ]; then
-        echo -ne "\e[1m$msg\e[0m ..."
+        incolor && echo -ne "\e[1m$msg\e[0m ..." || echo -n "$msg ..."
     else
-        echo -ne "> \e[1m$1\e[0m ..."
+        incolor && echo -ne "> \e[1m$1\e[0m ..." || echo -n "> $1 ..."
     fi
 
     # run cmd, capture stderr
@@ -80,18 +81,18 @@ check()
     ret=$?
     if [ -z "$cmpret" ]; then
         # ignored
-        echo -e "\e[1;34mignored\e[0m"
+        incolor && echo -e "\e[1;34mignored\e[0m" || echo "ignored"
     elif [ "$cmpret" -eq $ret ]; then
         # pass
-        echo -e "\e[1;32mpassed\e[0m"
+        incolor && echo -e "\e[1;32mpassed\e[0m" || echo "passed"
     else
         if [ "$WARNONLY" ]; then
             # warn
-            echo -e "\e[1;33mwarn\e[0m"
+            incolor && echo -e "\e[1;33mwarn\e[0m" || echo "warn"
             [ "$out" ] && echo "$out"
         else
             # fail
-            echo -e "\e[1;31mfailed\e[0m"
+            incolor && echo -e "\e[1;31mfailed\e[0m" || echo "failed"
             [ "$out" ] && echo "$out"
             CHECK_FAILED=1
         fi
